org.gradle.java.home=/home/axmdcl/jdk
org.gradle.jvmargs=-Xmx4608m -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:MaxMetaspaceSize=768m -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:ActiveProcessorCount=4 -Dcom.android.tools.r8.thread.count=1
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.enableAapt2Daemon=false
kotlin.daemon.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:ActiveProcessorCount=4
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.auto-detect=true
org.gradle.java.installations.paths=/home/axmdcl/jdk
